### ISSUE TITLE
Network support

### ISSUE THREAD

**Issue by bsapwindows** [andrakis/jorconsole#3]
Hi, @andrakis 

I'm playing with jorconsole and I think it's really cool project.

Currently the network isn't working for me. It says "No lease, failing". Could you guide me on how to fix it please?

And, I'm not quite sure if I understand jorconsole right. Does jorconsole compile code faster than normal jor1k in browser?

What I've been dreaming about is to see jor1k supports golang program, but currently there's no golang port for openrisc yet. So I'm thinking, if jorconsole compiles faster, maybe I could use it to build golang for jor1k myself?

Sorry if the questions sound stupid.

**Comment by andrakis** [comment]
Hello, and thanks for your interest!

Are you running with the `--network` option?

    node index.js --network

If this doesn't work, please ensure you have run `npm install`, as the WebSocket support is an npm module. If not present, the emulator continues without it (but prints a warning.)

I do not have `--network` enabled by default because I do not want to hammer the relay. I haven't yet managed to get a relay working locally myself, and in my debugging I did not want to be constantly connecting to the current relay and causing load issues.

The `--network` flag should do the trick though.

I'm not sure if it is faster than running in the browser, but it makes for easier debugging and trying to enhance the [Jor1K project](https://github.com/s-macke/jor1k). This project has also given me a lot of insight into how the Jor1K project works. Running it in a console allows you to make filesystem changes or emulator changes, and quickly test them. You can also add debugging statements or step through with a debugger to understand exactly how the whole emulator works.

I've been working on a native filesystem implementation, but it's not quite there yet. The goal is to allow you to boot JorConsole from a directory, and read/write changes to the filesystem (ie, persistence.) This would allow me to customize the emulator's Linux environment with whatever new services and setup I want. Ideally, I'd like to get a package system going for it so that one can install new software within the browser emulator, or have persistent storage and custom logins.

I'd love to get GoLang working on Jor1k. Part of the problem is the requirements for a cross compilation system (I'm not well versed in it), so I was hoping to download all the source libraries I need and compile everything on a server. Doing this within the browser is of course difficult - the relay isn't fast, the filesystem isn't persistent, it's just a lot of trouble.

Thank you for your questions, and hope this helps!

**Comment by andrakis** [comment]
@bsapwindows Has this helped?

**Comment by bsapwindows** [comment]
@andrakis  Yes it helped! Thank you for your detailed explanation and opinions! I understand the projects a lot now. Sorry for the late response. My shoulder was injured right after I asked for your help. I just left hospital yesterday. Today I saw your reply and I really appreciate it. Thanks again! :smiley:

**Comment by andrakis** [comment]
Glad to hear you're on the mend. Let me know if there's anything more you're interested in (feel free to reopen this issue to do so, or just comment here.)
